import "./globals.css";

export const metadata = {
  title: "Button Component",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#303030]">{children}</body>
    </html>
  );
}
