import type { Metadata } from "next";

import GlobalContextProvider from "@/context/globalContext";
import QueryProvider from "@/context/reactQuery";
import Footer from "@/components/ui/Footer";
import Header from "@/components/ui/Header";

import "material-symbols/outlined.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Github Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col p-3 lg:px-[120px] lg:py-8">
        <QueryProvider>
          <GlobalContextProvider>
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </GlobalContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
